events {}
http {
    include /etc/nginx/mime.types;
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        # Mocking app-server API for local testing if running WITHOUT proxy
        # But in docker-compose, the proxy handles this
        location /api/ {
            proxy_pass http://app-server:5000/api/;
        }
    }
}
