events {}
http {
    include /etc/nginx/mime.types;
    
    # Load balancing / Upstreaming
    upstream web_backend {
        server web-server:80;
    }

    upstream app_backend {
        server app-server:5000;
    }

    server {
        listen 80;
        server_name localhost myminicloud.local;

        # Web Server route
        location / {
            proxy_pass http://web_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Application Server API route
        location /api/ {
            proxy_pass http://app_backend/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Health Check route
        location /health {
            proxy_pass http://app_backend/health;
        }
    }
}
